import numpy as np


class PelletGrillSimulator:
    # Physics constants
    THERMAL_MASS = 50.0         # °F·s / heat unit — resistance to temperature change
    MAX_HEAT_OUTPUT = 45.0      # heat units when combustion is at full rate
    HEAT_LOSS_COEFF = 0.1       # heat loss per °F above ambient (Newton's law of cooling)
    AIRFLOW_LAG = 5.0           # time constant (s) for airflow to respond to fan speed changes
    FUEL_LAG = 3.0              # time constant (s) for fuel supply to respond to auger changes
    FAN_COOLING_COEFF = 0.01    # additional heat loss per unit fan speed per °F above ambient
    LID_LOSS_MULTIPLIER = 4.0   # multiplier on heat loss when lid is open

    def __init__(
        self,
        ambient_temperature: float = 70.0,
        timestep: float = 1.0,
    ):
        self.ambient_temperature = ambient_temperature
        self.timestep = timestep

        # Simulator state (hidden from agent)
        self.grill_temperature: float = ambient_temperature
        self.airflow: float = 0.0       # air reaching firepot, lags fan speed
        self.fuel_supply: float = 0.0   # pellets reaching firepot, lags auger feed rate
        self.lid_open: bool = False

        # Agent-visible state
        self.fan_speed: float = 0.0
        self.auger_feed_rate: float = 0.0

    def step(self, fan_speed: float, auger_feed_rate: float) -> tuple[float, float, float]:
        """
        Advance the simulation by one timestep.

        Combustion requires both air (fan) and fuel (auger). Each has its own
        lag. The actual burn rate is limited by whichever supply is lower, so
        the controller must balance both to maximise heat output.

        Args:
            fan_speed:       Desired fan speed, clamped to [0, 1].
            auger_feed_rate: Auger on/off signal — any value >= 0.5 turns the
                             auger on (1.0), below 0.5 turns it off (0.0).

        Returns:
            (grill_temperature, fan_speed, auger_feed_rate) — the agent-observable state.
        """
        self.fan_speed = float(np.clip(fan_speed, 0.0, 1.0))
        self.auger_feed_rate = 1.0 if auger_feed_rate >= 0.5 else 0.0

        # Airflow responds quickly to fan speed
        airflow_delta = (self.fan_speed - self.airflow) / self.AIRFLOW_LAG
        self.airflow = float(np.clip(
            self.airflow + airflow_delta * self.timestep, 0.0, 1.0
        ))

        # Fuel supply responds more slowly as pellets travel to the firepot and ignite
        fuel_delta = (self.auger_feed_rate - self.fuel_supply) / self.FUEL_LAG
        self.fuel_supply = float(np.clip(
            self.fuel_supply + fuel_delta * self.timestep, 0.0, 1.0
        ))

        # Combustion is limited by whichever is scarcer: air or fuel
        combustion_rate = min(self.airflow, self.fuel_supply)

        # Heat generated by combustion
        heat_in = combustion_rate * self.MAX_HEAT_OUTPUT

        # Heat lost to environment: base Newton cooling + forced convection from fan
        loss_coeff = self.HEAT_LOSS_COEFF * (self.LID_LOSS_MULTIPLIER if self.lid_open else 1.0)
        heat_loss = (loss_coeff + self.FAN_COOLING_COEFF * self.fan_speed) * (
            self.grill_temperature - self.ambient_temperature
        )

        # Net temperature change this timestep
        self.grill_temperature += (heat_in - heat_loss) / self.THERMAL_MASS * self.timestep

        return self.grill_temperature, self.fan_speed, self.auger_feed_rate

    def open_lid(self):
        self.lid_open = True

    def close_lid(self):
        self.lid_open = False

    def reset(self) -> tuple[float, float, float]:
        """Reset to initial state and return starting observation."""
        self.grill_temperature = self.ambient_temperature
        self.airflow = 0.0
        self.fuel_supply = 0.0
        self.fan_speed = 0.0
        self.auger_feed_rate = 0.0
        self.lid_open = False
        return self.grill_temperature, self.fan_speed, self.auger_feed_rate
