import numpy as np


class PelletGrillSimulator:
    # Physics constants
    THERMAL_MASS = 50.0         # °F·s / heat unit — resistance to temperature change
    MAX_HEAT_OUTPUT = 45.0      # heat units at fire_strength=1.0
    HEAT_LOSS_COEFF = 0.1       # heat loss per °F above ambient (Newton's law of cooling)
    FIRE_LAG = 15.0             # time constant (s) for fire to respond to auger changes
    LID_LOSS_MULTIPLIER = 4.0   # multiplier on heat loss when lid is open

    def __init__(
        self,
        ambient_temperature: float = 70.0,
        timestep: float = 1.0,
    ):
        self.ambient_temperature = ambient_temperature
        self.timestep = timestep

        # Simulator state (hidden from agent)
        self.grill_temperature: float = ambient_temperature
        self.fire_strength: float = 0.0
        self.lid_open: bool = False

        # Agent-visible state
        self.auger_feed_rate: float = 0.0

    def step(self, auger_feed_rate: float) -> tuple[float, float]:
        """
        Advance the simulation by one timestep.

        Args:
            auger_feed_rate: Desired auger rate, clamped to [0, 1].

        Returns:
            (grill_temperature, auger_feed_rate) — the agent-observable state.
        """
        self.auger_feed_rate = float(np.clip(auger_feed_rate, 0.0, 1.0))

        # Fire strength lags behind auger feed rate (pellets take time to ignite/die)
        fire_delta = (self.auger_feed_rate - self.fire_strength) / self.FIRE_LAG
        self.fire_strength = float(np.clip(
            self.fire_strength + fire_delta * self.timestep, 0.0, 1.0
        ))

        # Heat generated by combustion
        heat_in = self.fire_strength * self.MAX_HEAT_OUTPUT

        # Heat lost to environment (greater when lid is open)
        loss_coeff = self.HEAT_LOSS_COEFF * (self.LID_LOSS_MULTIPLIER if self.lid_open else 1.0)
        heat_loss = loss_coeff * (self.grill_temperature - self.ambient_temperature)

        # Net temperature change this timestep
        self.grill_temperature += (heat_in - heat_loss) / self.THERMAL_MASS * self.timestep

        return self.grill_temperature, self.auger_feed_rate

    def open_lid(self):
        self.lid_open = True

    def close_lid(self):
        self.lid_open = False

    def reset(self) -> tuple[float, float]:
        """Reset to initial state and return starting observation."""
        self.grill_temperature = self.ambient_temperature
        self.fire_strength = 0.0
        self.auger_feed_rate = 0.0
        self.lid_open = False
        return self.grill_temperature, self.auger_feed_rate
